import { useMemo, useState } from 'react'
import { FiCheck, FiPlus, FiTrash2, FiZap } from 'react-icons/fi'
import Button from '../../components/common/Button'; import Card from '../../components/common/Card'; import Input from '../../components/common/Input'; import Loading from '../../components/common/Loading'; import StatusMessage from '../../components/feedback/StatusMessage'; import useChecklist from '../../hooks/useChecklist'; import useMembers from '../../hooks/useMembers'; import useAuth from '../../hooks/useAuth'; import { canEditAnyContent, canEditOwnContent } from '../../utils/permissions'
import { buildSmartChecklistSuggestions, filterNewChecklistSuggestions } from '../../utils/checklistSuggestions'

const categoryLabels = { documentos: 'Documentos', checkin: 'Check-in', casa: 'Casa', saude: 'Saude', criancas: 'Criancas', pessoal: 'Pessoal', higiene: 'Higiene', eletronicos: 'Eletronicos', compartilhados: 'Compartilhados', outros: 'Outros' }
export default function ChecklistPage() {
  const { userProfile, trip } = useAuth(); const { members } = useMembers(); const { items, loading, error, addItem, toggleItem, deleteItem } = useChecklist()
  const [mode, setMode] = useState('task'); const [showForm, setShowForm] = useState(false); const [feedback, setFeedback] = useState('')
  const visible = useMemo(() => items.filter((item) => item.kind === mode), [items, mode]); const done = visible.filter((item) => item.done).length
  async function submit(event) { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); try { await addItem({ title: String(form.get('title')), kind: mode, category: String(form.get('category')), assignedTo: String(form.get('assignedTo') ?? ''), dueDate: String(form.get('dueDate') ?? ''), priority: String(form.get('priority') ?? 'normal') }); element.reset(); setShowForm(false); setFeedback('Item adicionado com sucesso.') } catch (err) { setFeedback(err.message ?? 'Nao foi possivel adicionar.') } }
  function confirmDelete(itemId) { if (window.confirm('Tem certeza que deseja excluir este item?')) deleteItem(itemId) }
  async function addSmartSuggestions() { const suggestions = filterNewChecklistSuggestions(items, buildSmartChecklistSuggestions(trip)); try { for (const suggestion of suggestions) { await addItem({ ...suggestion, assignedTo: '', dueDate: '' }) } setFeedback(suggestions.length ? `${suggestions.length} sugestão(ões) adicionada(s) para esta viagem.` : 'As sugestões inteligentes já estão na lista.') } catch (err) { setFeedback(err.message ?? 'Não foi possível adicionar as sugestões.') } }
  return <div className="space-y-4"><Card className="bg-[linear-gradient(135deg,#f0fdfa,#fff)]"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-teal-700">{mode === 'task' ? 'Checklist compartilhado' : 'Malas da familia'}</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">{done} de {visible.length} concluidos</h2></div><div className="flex h-14 w-14 items-center justify-center rounded-full bg-teal-700 text-white"><FiCheck size={28} /></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-teal-100"><div className="h-full bg-teal-600 transition-all" style={{ width: `${visible.length ? (done / visible.length) * 100 : 0}%` }} /></div></Card>
  <div className="grid grid-cols-2 gap-2"><Button variant={mode === 'task' ? 'primary' : 'secondary'} onClick={() => setMode('task')}>Preparativos</Button><Button variant={mode === 'packing' ? 'primary' : 'secondary'} onClick={() => setMode('packing')}>Lista de malas</Button></div>
  <div className="flex flex-wrap justify-end gap-2"><Button variant="secondary" icon={<FiZap />} onClick={addSmartSuggestions}>Sugerir checklist</Button><Button icon={<FiPlus />} onClick={() => setShowForm((v) => !v)}>Adicionar item</Button></div><StatusMessage message={feedback} tone={feedback.includes('adicionad') || feedback.includes('já estão') || feedback.includes('sucesso') ? 'success' : 'error'} />
  {showForm ? <Card><form className="space-y-3" onSubmit={submit}><Input name="title" label={mode === 'task' ? 'Tarefa' : 'Item da mala'} required /><label className="flex flex-col gap-2 text-sm font-medium text-slate-600"><span>Categoria</span><select name="category" className="rounded-2xl border border-slate-200 px-4 py-3">{Object.entries(categoryLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="flex flex-col gap-2 text-sm font-medium text-slate-600"><span>Responsavel</span><select name="assignedTo" className="rounded-2xl border border-slate-200 px-4 py-3"><option value="">Toda a familia</option>{members.map((member) => <option key={member.id} value={member.userId || member.id}>{member.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><Input name="dueDate" label="Prazo" type="date" /><label className="flex flex-col gap-2 text-sm font-medium text-slate-600"><span>Prioridade</span><select name="priority" className="rounded-2xl border border-slate-200 px-4 py-3"><option value="normal">Normal</option><option value="alta">Alta</option></select></label></div><Button type="submit" className="w-full">Salvar item</Button></form></Card> : null}
  {loading ? <Loading /> : null}{error ? <StatusMessage message={error} tone="error" /> : null}<div className="space-y-2">{visible.map((item) => { const member = members.find((entry) => [entry.id, entry.userId].includes(item.assignedTo)); const canDelete = canEditAnyContent(userProfile) || canEditOwnContent(userProfile, item); return <Card key={item.id} className={`flex items-center gap-3 ${item.done ? 'opacity-60' : ''}`}><button onClick={() => toggleItem(item.id, !item.done)} className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border ${item.done ? 'border-teal-600 bg-teal-600 text-white' : 'border-slate-300 bg-white text-transparent'}`}><FiCheck /></button><div className="min-w-0 flex-1"><p className={`font-semibold text-slate-900 ${item.done ? 'line-through' : ''}`}>{item.title}</p><p className="text-xs text-slate-500">{categoryLabels[item.category] ?? 'Outros'} · {member?.name ?? 'Toda a família'}{item.dueDate ? ` · até ${item.dueDate}` : ''}</p></div>{item.priority === 'alta' && !item.done ? <span className="rounded-full bg-rose-50 px-2 py-1 text-xs font-semibold text-rose-600">Urgente</span> : null}{canDelete ? <button onClick={() => confirmDelete(item.id)} className="p-2 text-rose-500" aria-label="Excluir"><FiTrash2 /></button> : null}</Card> })}</div></div>
}

