import {addDoc,collection,deleteDoc,doc,getDocs,query,setDoc,updateDoc,where,increment} from 'firebase/firestore';import {db,firebaseReady} from '../firebase/config';import type{Child,Execution,Routine,SensorySettings}from'../types'
const local=<T>(key:string):T[]=>JSON.parse(localStorage.getItem(key)||'[]');const save=(key:string,v:unknown)=>localStorage.setItem(key,JSON.stringify(v));const id=()=>crypto.randomUUID()
export async function listOwn<T>(name:string,userId:string,extra?:[string,string]){if(firebaseReady&&db){let q=query(collection(db,name),where('userId','==',userId));const snap=await getDocs(q);return snap.docs.map(d=>({id:d.id,...d.data()} as T)).filter(x=>!extra||(x as Record<string,string>)[extra[0]]===extra[1])}return local<T>(name).filter(x=>(x as Record<string,string>).userId===userId&&(!extra||(x as Record<string,string>)[extra[0]]===extra[1]))}
export async function create<T extends {id:string}>(name:string,value:Omit<T,'id'>){if(firebaseReady&&db){const ref=await addDoc(collection(db,name),value);return{id:ref.id,...value}as T}const next={id:id(),...value}as T;save(name,[...local<T>(name),next]);return next}
export async function update<T>(name:string,itemId:string,value:Partial<T>){if(firebaseReady&&db)return updateDoc(doc(db,name,itemId),value);save(name,local<T>(name).map(x=>(x as{id:string}).id===itemId?{...x,...value}:x))}
export async function remove(name:string,itemId:string){if(firebaseReady&&db)return deleteDoc(doc(db,name,itemId));save(name,local<{id:string}>(name).filter(x=>x.id!==itemId))}
export const childrenApi={list:(u:string)=>listOwn<Child>('children',u),create:(v:Omit<Child,'id'>)=>create<Child>('children',v),update:(id:string,v:Partial<Child>)=>update<Child>('children',id,v)}
export const routinesApi={list:(u:string)=>listOwn<Routine>('routines',u),create:(v:Omit<Routine,'id'>)=>create<Routine>('routines',v),update:(id:string,v:Partial<Routine>)=>update<Routine>('routines',id,v),remove:(id:string)=>remove('routines',id)}
export const executionsApi={list:(u:string)=>listOwn<Execution>('routineExecutions',u),create:(v:Omit<Execution,'id'>)=>create<Execution>('routineExecutions',v),update:(id:string,v:Partial<Execution>)=>update<Execution>('routineExecutions',id,v)}
export async function addStars(childId:string,stars:number){if(firebaseReady&&db)return updateDoc(doc(db,'children',childId),{stars:increment(stars)});const all=local<Child>('children');save('children',all.map(c=>c.id===childId?{...c,stars:c.stars+stars}:c))}
export async function loadSettings(userId:string,childId:string,defaults:SensorySettings){if(firebaseReady&&db){const rows=await listOwn<SensorySettings&{childId:string}>('sensorySettings',userId,['childId',childId]);return rows[0]||defaults}return JSON.parse(localStorage.getItem(`settings-${childId}`)||JSON.stringify(defaults))}
export async function saveSettings(userId:string,childId:string,v:SensorySettings){if(firebaseReady&&db)return setDoc(doc(db,'sensorySettings',`${userId}_${childId}`),{...v,userId,childId},{merge:true});localStorage.setItem(`settings-${childId}`,JSON.stringify(v))}
